local impatient_ok, impatient = pcall(require, "impatient")
if impatient_ok then
	impatient.enable_profile()
end

require("jorge.plugins-setup")
require("jorge.core.options")
require("jorge.core.keymaps")
require("jorge.core.colorscheme")
require("jorge.plugins.comment")
require("jorge.plugins.lualine")
require("jorge.plugins.telescope")
require("jorge.plugins.nvim-cmp")
require("jorge.plugins.lsp.mason")
require("jorge.plugins.lsp.lspsaga")
require("jorge.plugins.lsp.lspconfig")
require("jorge.plugins.lsp.null-ls")
require("jorge.plugins.autopairs")
require("jorge.plugins.treesitter")
require("jorge.plugins.gitsigns")
require("jorge.plugins.neo-tree")
require("jorge.plugins.bufferline")
require("jorge.plugins.aerial")
